apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-init
  namespace: mapreduce
spec:
  backoffLimit: 7
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-keycloak
          image: curlimages/curl:latest
          command:
            - sh
            - -c
            - |
              until curl -sf http://keycloak:8080/realms/master; do
                echo "Waiting for Keycloak..."
                sleep 5
              done
      containers:
        - name: keycloak-init
          image: ktistos/kcinit:latest
          imagePullPolicy: Always
          env:
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KC_BOOTSTRAP_ADMIN_USERNAME
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KC_BOOTSTRAP_ADMIN_PASSWORD
